server:
  port: 9292

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: jt-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.springframework.kafka: DEBUG
